[package]
name = "zune-heic"
version = "0.5.0"
edition = "2024"

[dependencies]
zune-core = { version = "0.5.1", path = "../zune-core" }

[features]
simd = []
default = ['simd']


[dev-dependencies]
criterion = "0.8.2"
libheif-rs = { version = "2.7.0",features = ["embedded-libheif"] } # Standard safe wrapper for libheif



[[bench]]
name = "heif_bench"
harness = false