name: Rust

on:
  push:
    branches: [ "main","dev","gif" ]
  pull_request:
    branches: [ "main","dev" ,"gif" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: Linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu

          - name: Windows
            os: windows-latest
            target: x86_64-pc-windows-msvc

          - name: MacOS
            os: macos-latest
            target: x86_64-apple-darwin

          # - name: Web
          #   os: ubuntu-latest
          #   target: wasm32-unknown-unknown

    runs-on: ${{ matrix.os }}


    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        if: matrix.name != 'Windows' # Windows sucks due to paths, and commands syntax
        run: RUSTFLAGS="-C debuginfo=2"  cargo test --verbose --release --workspace --no-fail-fast
      - name: Build with no features
        run: cargo c --no-default-features --workspace
      - name: Setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          target: ${{ matrix.target }}
          override: true

      - name: Check Basics
        uses: actions-rs/cargo@v1
        if: matrix.name != 'Windows' # Windows sucks due to paths, and command syntac
        with:
          command: test
          args: --target ${{ matrix.target }} --workspace --all --no-default-features

